/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112991-g081d69b78d-20231215"
#endif /* AVUTIL_FFVERSION_H */
